name: Postman Test and HTML Report Action

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 18 * * 3' # Runs every Wednesday at 7:30pm
    - cron: '30 18 * * 5' # Runs every Friday at 7:30pm
    - cron: '0 20 * * 0' # Runs every Sunday at 8:00pm

jobs:
  run_tests:
    if: github.event_name == 'schedule' || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install newman and newman-reporter-html
        run: |
          npm install -g newman newman-reporter-html
          echo "Newman and newman-reporter-html installed."

      - name: Run Postman tests
        if: always()
        continue-on-error: true
        run: |
          newman run Postman-Collections/Postman-Collection.json --reporters cli,html --reporter-html-export newman-report.html
          echo "Postman tests run."

      - name: Deploy HTML report to GitHub Pages
        id: deploy
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./
        # with:
        #   cname: 'your-custom-domain.com'

      - name: Notify Slack
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: 'C070KUKPDLZ'
          SLACK_MESSAGE: |
            *Wholistic Organization - API Quality Readiness*
            *Contributors - Azeez*
            Status: ${{ job.status }}
            Check the HTML report at: ${{ secrets.PAGES_URL }}/newman-report.html
